memory_limit = 1G
max_execution_time = 3600
max_input_time = 3600
upload_max_filesize = 16G
post_max_size = 16G
max_file_uploads = 100
date.timezone = Asia/Tehran

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256
opcache.revalidate_freq = 60
opcache.save_comments = 1
opcache.validate_timestamps = 0

[apcu]
apc.enable_cli = 1
apc.shm_size = 256M
